### PR TITLE
2.10.0

### PR DESCRIPTION
**Pull request by navanchauhan**
- updated to 2.10.0
- bump version
- added mysql db
- tweaked defaults
- hint for port

### CODE REVIEW

**Comment by navanchauhan** [comment]
What Works Now (Which did not work before):
* Plaintext and Secure Mode (6667, 6697)
* Automatic Certificate Management (By adding to `ssl-cert` group)
* Server Admin using `/oper admin` (Default Password `ergo@YunoHost`)

What Needs to Be Done:
* Configurable Server Password during app creation
* Verify E-Mail setup for NickServ
* Backup MOTD/CONFIG?

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
@ericgaspar can you give me write access to this repository so I can maintain this package?

**Comment by ericgaspar** [comment]
> @ericgaspar can you give me write access to this repository so I can maintain this package?

you should have maintainer access now. I completely forgot about this app and what it does... 😅

**Comment by navanchauhan** [comment]
> > @ericgaspar can you give me write access to this repository so I can maintain this package?
> 
> you should have maintainer access now. I completely forgot about this app and what it does... 😅

You can use ergo to run your own IRC server!

**Comment by ericgaspar** [comment]
That is cool. Thanks for taking over the package!

You may also be interested by gamja (a simple IRC web client) used by sourcehut forge https://github.com/YunoHost-Apps/gamja_ynh

**Comment by navanchauhan** [comment]
I definitely will do, if I need it. Thanks for your help!

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Pull request merged**
